name: daonsushi
description: daon menu.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  carousel_slider: ^4.1.1

flutter:

  uses-material-design: true
  assets:
  - assets/
  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans.ttc
    - family: Rockwell
      fonts:
        - asset: fonts/Rockwell.ttc
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700



